export const TYPES = {
  ADD_USERS: "ADD_USER",
  REMOVE_USER: "REMOVE_USER",
  LOG_OUT_USER: "LOG_OUT_USER",
  VERIFIED_USER: "VERIFIED_USER",
  LOG_USER: "LOG_USER",
  TOKEN_USER: "TOKEN_USER",
  ADD_FAV_USER: "ADD_FAV_USER",
  REMOVE_FAV_USER: "REMOVE_FAV_USER",
  ALL_FAV_USER: "ALL_FAV_USER",
  REMOVE_ALL_FAV_USER: "REMOVE_ALL_FAV_USER", //Ver si esto es necesario pero por las dudas lo creo y después lo depuro
  REMOVE_ALL_USER: "REMOVE_ALL_USER",
};
