export const TYPES = {
  PRODUCT_RANDOM: "PRODUCT_RANDOM",
  PRODUCT_CATEGORY: "PRODUCT_CATEGORY",
  PRODUCT_LOCATION: "PRODUCT_LOCATION",
  HOSTEL_CATEGORY: "HOSTEL_CATEGORY",
  DEPARTAMENTO_CATEGORY: "DEPARTAMENTO_CATEGORY",
  CASA_CATEGORY: "CASA_CATEGORY",
};
